Dataset: Amazon Sales Dataset

Link: https://www.kaggle.com/datasets/karkavelrajaj/amazon-sales-dataset

License:
CC BY-NC-SA 4.0

Features

product_id - Product ID

product_name - Name of the Product

category - Category of the Product

discounted_price - Discounted
Price of the Product

actual_price - Actual Price of the Product

discount_percentage - Percentage of Discount for the Product

rating - Rating of the Product

rating_count - Number of people who voted for the Amazon rating

about_product - Description about the Product

user_id - ID of the user who wrote
review for the Product

user_name - Name of the user who wrote review for the Product

review_id - ID of the user review

review_title - Short review

review_content - Long review

img_link - Image Link of the Product

product_link - Official Website Link of the Product

**Data Preparation**

**1. Structure Understanding**

Load the data

In [ ]:
import pandas as pd
data=pd.read_csv("/content/amazon.csv")
df=pd.DataFrame(data)
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [ ]:
df.shape

(1465, 16)

**Data Types**

In [ ]:
df.dtypes

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

Convert the necessary object data types to integer/numeric

In [ ]:
columns_to_clean = ['discounted_price', 'actual_price',
                 'discount_percentage', 'rating', 'rating_count']

for col in columns_to_clean:
    # Explicitly convert to string type to ensure .str accessor works
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('₹', '', regex=False)\
                     .str.replace(',', '', regex=False)\
                     .str.replace('%', '', regex=False)

    df[col] = pd.to_numeric(df[col], errors='coerce')

Identifying the Numeric and Categorical Columns

In [ ]:
print("\nNumeric Columns:")
print(df.select_dtypes(include='number').columns)

print("\Categorical Columns:")
print(df.select_dtypes(include='object').columns)

Numeric Columns:
Index(['discounted_price', 'actual_price', 'discount_percentage', 'rating',
       'rating_count'],
      dtype='object')
\Categorical Columns:
Index(['product_id', 'product_name', 'category', 'about_product', 'user_id',
       'user_name', 'review_id', 'review_title', 'review_content', 'img_link',
       'product_link'],
      dtype='object')

<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
/tmp/ipython-input-703/2222843098.py:4: SyntaxWarning: invalid escape sequence '\C'
  print("\Categorical Columns:")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   int64
 6   rating               1464 non-null   float64
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: float64(4), int64(1), object(11)
memory usage: 183.3+ KB

Count the Unique values

Count the actual unique values

In [ ]:
df['rating'].unique()

array([4.2, 4. , 3.9, 4.1, 4.3, 4.4, 4.5, 3.7, 3.3, 3.6, 3.4, 3.8, 3.5,
       4.6, 3.2, 5. , 4.7, 3. , 2.8, 3.1, 4.8, 2.3, nan, 2. , 2.6, 2.9])

Check the duplicates rowise

In [ ]:
df.duplicated().sum()

np.int64(0)

Check the duplicates of unique category

In [ ]:
df.duplicated(subset=['product_id']).sum()

np.int64(114)

In [ ]:
df.duplicated(subset=['user_id']).sum()

np.int64(271)

In [ ]:
df.duplicated(subset=['product_id','user_id']).sum()

np.int64(104)

In [ ]:
df.duplicated(subset=['review_id']).sum()

np.int64(271)

In [ ]:
df.duplicated(subset=['product_id','user_id','review_id']).sum()

np.int64(104)

In [ ]:
df.duplicated(subset=['review_id','review_title','review_content']).sum()

np.int64(253)

In [ ]:
df.duplicated(subset=['product_id','user_id']).sum()

np.int64(104)

In [ ]:
df.duplicated(subset=['rating_count']).sum()

np.int64(321)

In [ ]:
df.duplicated(subset=['rating']).sum()

np.int64(1439)

Handling missing values

In [ ]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 1
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [ ]:
df[df['rating'].isna()]

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1279,B08L12N5H1,Eureka Forbes car Vac 100 Watts Powerful Sucti...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",2099.0,2499.0,16,NaN,992.0,No Installation is provided for this product|1...,"AGTDSNT2FKVYEPDPXAA673AIS44A,AER2XFSWNN4LAUCJ5...","Divya,Dr Nefario,Deekshith,Preeti,Prasanth R,P...","R2KKTKM4M9RDVJ,R1O692MZOBTE79,R2WRSEWL56SOS4,R...","Decent product,doesn't pick up sand,Ok ok,Must...","Does the job well,doesn't work on sand. though...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Vacuum-Cle...

In [ ]:
df[df['rating_count'].isna()]

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
282,B0B94JPY2N,Amazon Brand - Solimo 65W Fast Charging Braide...,Computers&Accessories|Accessories&Peripherals|...,199.0,999.0,80,3.0,NaN,USB C to C Cable: This cable has type C connec...,AE7CFHY23VAJT2FI4NZKKP6GS2UQ,Pranav,RUB7U91HVZ30,The cable works but is not 65W as advertised,I have a pd supported car charger and I bought...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Amazon-Brand-Charging-Su...
324,B0BQRJ3C47,"REDTECH USB-C to Lightning Cable 3.3FT, [Apple...",Computers&Accessories|Accessories&Peripherals|...,249.0,999.0,75,5.0,NaN,💎[The Fastest Charge] - This iPhone USB C cabl...,AGJC5O5H5BBXWUV7WRIEIOOR3TVQ,Abdul Gafur,RQXD5SAMMPC6L,Awesome Product,Quick delivery.Awesome ProductPacking was good...,https://m.media-amazon.com/images/I/31-q0xhaTA...,https://www.amazon.in/REDTECH-Lightning-Certif...

In [ ]:
df[df["product_id"] == "B08L12N5H1"]

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1279,B08L12N5H1,Eureka Forbes car Vac 100 Watts Powerful Sucti...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",2099.0,2499.0,16,NaN,992.0,No Installation is provided for this product|1...,"AGTDSNT2FKVYEPDPXAA673AIS44A,AER2XFSWNN4LAUCJ5...","Divya,Dr Nefario,Deekshith,Preeti,Prasanth R,P...","R2KKTKM4M9RDVJ,R1O692MZOBTE79,R2WRSEWL56SOS4,R...","Decent product,doesn't pick up sand,Ok ok,Must...","Does the job well,doesn't work on sand. though...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Vacuum-Cle...

Drop the unnecessary columns/attributes

In [ ]:
# Drop unncessary columns/attributes which are not needed for analysis
df.drop([
    'img_link',
    'product_link',
    'user_id',
    'user_name',
    'review_id',
    'review_title',
    'review_content',
    'about_product'
], axis=1, inplace=True)

In [ ]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64,4.2,24269.0
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43,4.0,43994.0
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90,3.9,7928.0
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53,4.2,94363.0
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61,4.2,16905.0

**Feature Engineering**

In [ ]:
#Split the categories
split_cols = df['category'].str.split('|', expand=True)
split_cols.head()

,0,1,2,3,4,5,6
0,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,None,None
1,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,None,None
2,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,None,None
3,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,None,None
4,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,None,None

In [ ]:
df['category'].str.split('|', expand=True).shape

(1465, 7)

In [ ]:
df[['Root (Department)',
    'Category',
    'Sub_category',
    'Sub-sub_category',
    'Product_type']] = split_cols[[0,1,2,3,4]]

df.drop(['category'], axis=1, inplace=True)
df.head()

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,399.0,1099.0,64,4.2,24269.0,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,199.0,349.0,43,4.0,43994.0,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,199.0,1899.0,90,3.9,7928.0,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,329.0,699.0,53,4.2,94363.0,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,154.0,399.0,61,4.2,16905.0,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables

**2. Data Quality Check**

**Data Cleaning and Text Normalization**

In [ ]:
df['Root (Department)'] = df['Root (Department)'].str.replace('&', ' & ')
df['Category'] = df['Category'].str.replace('&', ' & ')
df['Sub_category'] = df['Sub_category'].str.replace('&', ' & ')
df.head()

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,399.0,1099.0,64,4.2,24269.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,199.0,349.0,43,4.0,43994.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,199.0,1899.0,90,3.9,7928.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,329.0,699.0,53,4.2,94363.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,154.0,399.0,61,4.2,16905.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables

In [ ]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1465.000000,1465.000000,1465.000000,1464.000000,1463.000000
mean,3125.310874,5444.990635,47.691468,4.096585,18295.541353
std,6944.304394,10874.826864,21.635905,0.291674,42753.864952
min,39.000000,39.000000,0.000000,2.000000,2.000000
25%,325.000000,800.000000,32.000000,4.000000,1186.000000
50%,799.000000,1650.000000,50.000000,4.100000,5179.000000
75%,1999.000000,4295.000000,63.000000,4.300000,17336.500000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

Handling the missing values logically

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   1
rating_count             2
Root (Department)        0
Category                 0
Sub_category             8
Sub-sub_category       165
Product_type           943
dtype: int64

Finding which row has NA values in 'Rating'

In [ ]:
df[df['rating'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
1279,B08L12N5H1,Eureka Forbes car Vac 100 Watts Powerful Sucti...,2099.0,2499.0,16,NaN,992.0,Home & Kitchen,Kitchen & HomeAppliances,"Vacuum,Cleaning & Ironing",Vacuums&FloorCare,Vacuums

Average rating of all Departments

In [ ]:
df.groupby('Root (Department)')['rating'].mean()

Root (Department)
Car & Motorbike            3.800000
Computers & Accessories    4.154967
Electronics                4.081749
Health & PersonalCare      4.000000
Home & Kitchen             4.040716
HomeImprovement            4.250000
MusicalInstruments         3.900000
OfficeProducts             4.309677
Toys & Games               4.300000
Name: rating, dtype: float64

Getting the unique values of the specfic departments sub-category options

In [ ]:
df[df['Root (Department)'] == 'Home & Kitchen']['Sub_category'].unique()

array(['Scrapbooking', 'PaintingMaterials', 'DrawingMaterials',
       'SmallKitchenAppliances', 'RoomHeaters',
       'Vacuum,Cleaning & Ironing', 'KitchenTools',
       'WaterHeaters & Geysers', 'LaundryOrganization', 'Fans',
       'Coffee,Tea & Espresso', 'WaterPurifiers & Accessories',
       'AirPurifiers', 'SewingMachines & Accessories', 'Humidifiers',
       'AirConditioners', 'Parts & Accessories'], dtype=object)

In [ ]:
df[df['Root (Department)'] == 'Home & Kitchen'] \
    .groupby('Sub_category')['rating'] \
    .mean()

Sub_category
AirConditioners                 4.300000
AirPurifiers                    4.275000
Coffee,Tea & Espresso           4.006667
DrawingMaterials                4.350000
Fans                            4.088235
Humidifiers                     3.966667
KitchenTools                    4.100000
LaundryOrganization             4.025000
PaintingMaterials               4.450000
Parts & Accessories             4.100000
RoomHeaters                     3.834783
Scrapbooking                    3.900000
SewingMachines & Accessories    3.650000
SmallKitchenAppliances          4.056354
Vacuum,Cleaning & Ironing       4.076543
WaterHeaters & Geysers          4.081818
WaterPurifiers & Accessories    4.050000
Name: rating, dtype: float64

Filling the NA values grouping with the department

In [ ]:
df['rating'] = df.groupby('Root (Department)')['rating'] \
                 .transform(lambda x: x.fillna(x.mean()))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             2
Root (Department)        0
Category                 0
Sub_category             8
Sub-sub_category       165
Product_type           943
dtype: int64

Checking out the specfic result

In [ ]:
df.iloc[1279]

product_id                                                    B08L12N5H1
product_name           Eureka Forbes car Vac 100 Watts Powerful Sucti...
discounted_price                                                  2099.0
actual_price                                                      2499.0
discount_percentage                                                   16
rating                                                          4.040716
rating_count                                                       992.0
Root (Department)                                         Home & Kitchen
Category                                        Kitchen & HomeAppliances
Sub_category                                   Vacuum,Cleaning & Ironing
Sub-sub_category                                       Vacuums&FloorCare
Product_type                                                     Vacuums
Name: 1279, dtype: object

Getting the median of the rating count based on the Department

In [ ]:
df.groupby('Root (Department)')['rating_count'].apply(lambda x: x.median())

Root (Department)
Car & Motorbike             1118.0
Computers & Accessories     7732.0
Electronics                10689.0
Health & PersonalCare       3663.0
Home & Kitchen              2305.5
HomeImprovement             4283.0
MusicalInstruments         44441.0
OfficeProducts              4426.0
Toys & Games               15867.0
Name: rating_count, dtype: float64

In [ ]:
df[df['rating_count'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
282,B0B94JPY2N,Amazon Brand - Solimo 65W Fast Charging Braide...,199.0,999.0,80,3.0,NaN,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
324,B0BQRJ3C47,"REDTECH USB-C to Lightning Cable 3.3FT, [Apple...",249.0,999.0,75,5.0,NaN,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables

Filling the NA values of the rating count using median of the depeartment level.

In [ ]:
df['rating_count'] = df.groupby('Root (Department)')['rating_count'] \
                 .transform(lambda x: x.fillna(x.median()))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             8
Sub-sub_category       165
Product_type           943
dtype: int64

Handling missing values of Sub-Category

In [ ]:
df[df['Sub_category'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
662,B08HLZ28QC,Oakter Mini UPS for 12V WiFi Router Broadband ...,1199.0,3490.0,66,4.1,11716.0,Computers & Accessories,NetworkingDevices,None,None,None
674,B00LVMTA2A,Panasonic CR-2032/5BE Lithium Coin Battery - P...,225.0,250.0,10,4.4,26556.0,Electronics,GeneralPurposeBatteries & BatteryChargers,None,None,None
709,B08L879JSN,Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920...,6299.0,13750.0,54,4.2,2014.0,Computers & Accessories,Monitors,None,None,None
903,B08Y5QJTVK,"Duracell CR2025 3V Lithium Coin Battery, 5 pcs...",116.0,200.0,42,4.4,357.0,Electronics,GeneralPurposeBatteries & BatteryChargers,None,None,None
913,B08Y57TPDM,"Duracell CR2016 3V Lithium Coin Battery, 5 pcs...",116.0,200.0,42,4.3,485.0,Electronics,GeneralPurposeBatteries & BatteryChargers,None,None,None
922,B08J82K4GX,"Samsung 24-inch(60.46cm) FHD Monitor, IPS, 75 ...",10099.0,19110.0,47,4.3,2623.0,Computers & Accessories,Monitors,None,None,None
965,B075DB1F13,"Panasonic Eneloop BQ-CC55N Advanced, Smart and...",1500.0,1500.0,0,4.4,25996.0,Electronics,GeneralPurposeBatteries & BatteryChargers,None,None,None
976,B09XXZXQC1,Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz R...,26999.0,37999.0,29,4.6,2886.0,Computers & Accessories,Tablets,None,None,None

In [ ]:
df[['Category', 'Sub_category']].value_counts()

Category                   Sub_category
Accessories & Peripherals  Cables & Accessories         240
Kitchen & HomeAppliances   SmallKitchenAppliances       181
HomeTheater,TV & Video     Accessories                   86
Mobiles & Accessories      MobileAccessories             84
Kitchen & HomeAppliances   Vacuum,Cleaning & Ironing     82
                                                       ...
HomeTheater,TV & Video     AVReceivers & Amplifiers       1
Kitchen & Dining           KitchenTools                   1
Laptops                    TraditionalLaptops             1
NetworkingDevices          DataCards & Dongles            1
PowerAccessories           SurgeProtectors                1
Name: count, Length: 74, dtype: int64

In [ ]:
df['Sub_category'] = df.groupby('Category')['Sub_category'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.iloc[674]

product_id                                                    B00LVMTA2A
product_name           Panasonic CR-2032/5BE Lithium Coin Battery - P...
discounted_price                                                   225.0
actual_price                                                       250.0
discount_percentage                                                   10
rating                                                               4.4
rating_count                                                     26556.0
Root (Department)                                            Electronics
Category                       GeneralPurposeBatteries & BatteryChargers
Sub_category                                         DisposableBatteries
Sub-sub_category                                                    None
Product_type                                                        None
Name: 674, dtype: object

In [ ]:
df[df['Category'] == 'GeneralPurposeBatteries & BatteryChargers']['Sub_category'].value_counts()

Sub_category
DisposableBatteries      11
RechargeableBatteries     3
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             3
Sub-sub_category       165
Product_type           943
dtype: int64

In [ ]:
df[df['Sub_category'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
709,B08L879JSN,Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920...,6299.0,13750.0,54,4.2,2014.0,Computers & Accessories,Monitors,None,None,None
922,B08J82K4GX,"Samsung 24-inch(60.46cm) FHD Monitor, IPS, 75 ...",10099.0,19110.0,47,4.3,2623.0,Computers & Accessories,Monitors,None,None,None
976,B09XXZXQC1,Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz R...,26999.0,37999.0,29,4.6,2886.0,Computers & Accessories,Tablets,None,None,None

In [ ]:
df[df['Category'] == 'Monitors']['Sub_category'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df[df['Category'] == 'Tablets']['Sub_category'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df[['Root (Department)', 'Sub_category']].value_counts()

Root (Department)        Sub_category
Computers & Accessories  Cables & Accessories          240
Home & Kitchen           SmallKitchenAppliances        181
Electronics              Accessories                    97
                         MobileAccessories              84
Home & Kitchen           Vacuum,Cleaning & Ironing      82
                                                      ...
                         Parts & Accessories             1
                         Scrapbooking                    1
HomeImprovement          Adapters & Multi-Outlets        1
                         CordManagement                  1
Toys & Games             Drawing & PaintingSupplies      1
Name: count, Length: 72, dtype: int64

In [ ]:
df['Sub_category'] = df.groupby('Root (Department)')['Sub_category'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category       165
Product_type           943
dtype: int64

In [ ]:
df[df['Category'] == 'Monitors']['Sub_category'].value_counts()

Sub_category
Cables & Accessories    2
Name: count, dtype: int64

Handling missing values of Sub-Sub Category

In [ ]:
df[['Category', 'Sub_category','Sub-sub_category']].value_counts()

Category                          Sub_category                Sub-sub_category
Accessories & Peripherals         Cables & Accessories        Cables                        237
Mobiles & Accessories             Smartphones & BasicMobiles  Smartphones                    68
HomeTheater,TV & Video            Televisions                 SmartTelevisions               63
Kitchen & HomeAppliances          Vacuum,Cleaning & Ironing   Irons,Steamers&Accessories     58
Headphones,Earbuds & Accessories  Headphones                  In-Ear                         52
                                                                                           ...
NetworkingDevices                 NetworkAdapters             PowerLANAdapters                1
OfficePaperProducts               Paper                       Copy&PrintingPaper              1
OfficeElectronics                 Calculators                 Financial&Business              1
Printers,Inks & Accessories       Inks,Toners & Cartridges    InkjetInkRefills&Kits           1
                                                              TonerCartridges                 1
Name: count, Length: 138, dtype: int64

In [ ]:
df[df['Sub-sub_category'] == 'TonerCartridges']

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
987,B07KNM95JK,Foxin FTC 12A / Q2612A Black Laser Toner Cartr...,598.0,1150.0,48,4.1,2535.0,Computers & Accessories,"Printers,Inks & Accessories","Inks,Toners & Cartridges",TonerCartridges,None

In [ ]:
df[df['Sub-sub_category'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
157,B088Z1YWBC,EGate i9 Pro-Max 1080p Native Full HD Projecto...,9490.0,15990.0,41,3.9,10480.0,Electronics,"HomeTheater,TV & Video",Projectors,None,None
210,B0BLV1GNLN,WZATCO Pixel | Portable LED Projector | Native...,6490.0,9990.0,35,4.0,27.0,Electronics,"HomeTheater,TV & Video",Projectors,None,None
268,B0978V2CP6,Cubetek 3 in 1 LCD Display V5.0 Bluetooth Tran...,1990.0,3100.0,36,4.0,897.0,Electronics,"HomeTheater,TV & Video",AVReceivers & Amplifiers,None,None
299,B0BNDD9TN6,WANBO X1 Pro (Upgraded) | Native 1080P Full HD...,13990.0,28900.0,52,4.5,7.0,Electronics,"HomeTheater,TV & Video",Projectors,None,None
334,B0BF57RN3K,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91,4.2,13937.0,Electronics,WearableTechnology,SmartWatches,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
1100,B00KRCBA6E,Maharaja Whiteline Lava Neo 1200-Watts Halogen...,2499.0,5000.0,50,3.8,1889.0,Home & Kitchen,"Heating,Cooling & AirQuality",RoomHeaters,None,None
1224,B08S6RKT4L,Balzano High Speed Nutri Blender/Mixer/Smoothi...,2599.0,4290.0,39,4.4,2116.0,Home & Kitchen,Kitchen & HomeAppliances,SmallKitchenAppliances,None,None
1274,B01M69WCZ6,Allin Exporters J66 Ultrasonic Humidifier Cool...,2249.0,3550.0,37,4.0,3973.0,Home & Kitchen,"Heating,Cooling & AirQuality",Humidifiers,None,None
1407,B09P182Z2H,"AGARO Glory Cool Mist Ultrasonic Humidifier, 4...",3290.0,5799.0,43,4.3,168.0,Home & Kitchen,"Heating,Cooling & AirQuality",Humidifiers,None,None
1445,B0B97D658R,Larrito wooden Cool Mist Humidifiers Essential...,499.0,799.0,38,3.6,212.0,Home & Kitchen,"Heating,Cooling & AirQuality",Humidifiers,None,None

In [ ]:
df['Sub-sub_category'] = df.groupby(['Category', 'Sub_category'])['Sub-sub_category'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.iloc[1224]

product_id                                                    B08S6RKT4L
product_name           Balzano High Speed Nutri Blender/Mixer/Smoothi...
discounted_price                                                  2599.0
actual_price                                                      4290.0
discount_percentage                                                   39
rating                                                               4.4
rating_count                                                      2116.0
Root (Department)                                         Home & Kitchen
Category                                        Kitchen & HomeAppliances
Sub_category                                      SmallKitchenAppliances
Sub-sub_category                              Kettles&HotWaterDispensers
Product_type                                                        None
Name: 1224, dtype: object

In [ ]:
df[df['Sub-sub_category']=='Kettles&HotWaterDispensers'][['Category', 'Sub_category']].value_counts()

Category                  Sub_category
Kitchen & HomeAppliances  SmallKitchenAppliances    33
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category       156
Product_type           943
dtype: int64

In [ ]:
df[df['Sub-sub_category'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
157,B088Z1YWBC,EGate i9 Pro-Max 1080p Native Full HD Projecto...,9490.0,15990.0,41,3.9,10480.0,Electronics,"HomeTheater,TV & Video",Projectors,None,None
210,B0BLV1GNLN,WZATCO Pixel | Portable LED Projector | Native...,6490.0,9990.0,35,4.0,27.0,Electronics,"HomeTheater,TV & Video",Projectors,None,None
268,B0978V2CP6,Cubetek 3 in 1 LCD Display V5.0 Bluetooth Tran...,1990.0,3100.0,36,4.0,897.0,Electronics,"HomeTheater,TV & Video",AVReceivers & Amplifiers,None,None
299,B0BNDD9TN6,WANBO X1 Pro (Upgraded) | Native 1080P Full HD...,13990.0,28900.0,52,4.5,7.0,Electronics,"HomeTheater,TV & Video",Projectors,None,None
334,B0BF57RN3K,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91,4.2,13937.0,Electronics,WearableTechnology,SmartWatches,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
1012,B014SZPBM4,"Duracell Ultra Alkaline D Battery, 2 Pcs",380.0,400.0,5,4.4,2111.0,Electronics,GeneralPurposeBatteries & BatteryChargers,DisposableBatteries,None,None
1014,B0B2RBP83P,"Lenovo IdeaPad 3 11th Gen Intel Core i3 15.6"" ...",37247.0,59890.0,38,4.0,323.0,Computers & Accessories,Laptops,TraditionalLaptops,None,None
1274,B01M69WCZ6,Allin Exporters J66 Ultrasonic Humidifier Cool...,2249.0,3550.0,37,4.0,3973.0,Home & Kitchen,"Heating,Cooling & AirQuality",Humidifiers,None,None
1407,B09P182Z2H,"AGARO Glory Cool Mist Ultrasonic Humidifier, 4...",3290.0,5799.0,43,4.3,168.0,Home & Kitchen,"Heating,Cooling & AirQuality",Humidifiers,None,None
1445,B0B97D658R,Larrito wooden Cool Mist Humidifiers Essential...,499.0,799.0,38,3.6,212.0,Home & Kitchen,"Heating,Cooling & AirQuality",Humidifiers,None,None

In [ ]:
df[['Category','Sub-sub_category']].value_counts()

Category                          Sub-sub_category
Accessories & Peripherals         Cables                        237
Mobiles & Accessories             Smartphones                    68
HomeTheater,TV & Video            SmartTelevisions               63
Kitchen & HomeAppliances          Irons,Steamers&Accessories     58
Headphones,Earbuds & Accessories  In-Ear                         52
                                                               ...
NetworkingDevices                 PowerLANAdapters                1
OfficePaperProducts               Copy&PrintingPaper              1
OfficeElectronics                 Financial&Business              1
Printers,Inks & Accessories       InkjetInkRefills&Kits           1
                                  TonerCartridges                 1
Name: count, Length: 138, dtype: int64

In [ ]:
df['Sub-sub_category'] = df.groupby(['Category'])['Sub-sub_category'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category       122
Product_type           943
dtype: int64

In [ ]:
df[['Sub_category','Sub-sub_category']].value_counts()

Sub_category                Sub-sub_category
Cables & Accessories        Cables                        237
Smartphones & BasicMobiles  Smartphones                    68
Televisions                 SmartTelevisions               63
Vacuum,Cleaning & Ironing   Irons,Steamers&Accessories     58
Headphones                  In-Ear                         52
                                                         ...
SmallKitchenAppliances      YogurtMakers                    1
                            StandMixers                     1
TabletAccessories           Stands                          1
UninterruptedPowerSupplies  Cables                          1
VideoCameras                DomeCameras                     1
Name: count, Length: 151, dtype: int64

In [ ]:
df['Sub-sub_category'] = df.groupby(['Sub_category'])['Sub-sub_category'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category       119
Product_type           943
dtype: int64

In [ ]:
df[['Root (Department)','Sub-sub_category']].value_counts()

Root (Department)        Sub-sub_category
Computers & Accessories  Cables                        249
Electronics              Smartphones                    68
                         SmartTelevisions               67
Home & Kitchen           Irons,Steamers&Accessories     58
Electronics              In-Ear                         56
                                                      ...
Home & Kitchen           YogurtMakers                    1
OfficeProducts           Copy&PrintingPaper              1
                         Basic                           1
                         Financial&Business              1
Toys & Games             ColouringPens&Markers           1
Name: count, Length: 138, dtype: int64

In [ ]:
df['Sub-sub_category'] = df.groupby(['Root (Department)'])['Sub-sub_category'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category         4
Product_type           943
dtype: int64

In [ ]:
df[df['Sub-sub_category'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
613,B076B8G5D8,Boya ByM1 Auxiliary Omnidirectional Lavalier C...,798.0,1995.0,60,4.0,68664.0,MusicalInstruments,Microphones,Condenser,None,None
800,B07JF9B592,MAONO AU-400 Lavalier Auxiliary Omnidirectiona...,478.0,699.0,32,3.8,20218.0,MusicalInstruments,Microphones,Condenser,None,None
805,B07WKBD37W,ESnipe Mart Worldwide Travel Adapter with Buil...,425.0,999.0,57,4.0,2581.0,HomeImprovement,Electrical,Adapters & Multi-Outlets,None,None
982,B07R99NBVB,"Gizga Essentials Cable Organiser, Cord Managem...",249.0,599.0,58,4.5,5985.0,HomeImprovement,Electrical,CordManagement,None,None

In [ ]:
df[df['Root (Department)']=='MusicalInstruments']['Sub-sub_category'].unique()

array([None], dtype=object)

In [ ]:
df[df['Category']=='Electrical'][['Sub-sub_category']].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df.shape

(1465, 12)

Drop the rows still having values in Sub-sub Category

This process done because there no relationship between other attributes

In [ ]:
df = df.dropna(subset=['Sub-sub_category'])

In [ ]:
df[df['Sub-sub_category'].isna()]

Empty DataFrame
Columns: [product_id, product_name, discounted_price, actual_price, discount_percentage, rating, rating_count, Root (Department), Category, Sub_category, Sub-sub_category, Product_type]
Index: []

In [ ]:
df.shape

(1461, 12)

Handling missing values in Prodcut type

In [ ]:
df.head()

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,399.0,1099.0,64,4.2,24269.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,199.0,349.0,43,4.0,43994.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,199.0,1899.0,90,3.9,7928.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,329.0,699.0,53,4.2,94363.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,154.0,399.0,61,4.2,16905.0,Computers & Accessories,Accessories & Peripherals,Cables & Accessories,Cables,USBCables

In [ ]:
df[['Sub-sub_category','Product_type']].value_counts()

Sub-sub_category                 Product_type
Cables                           USBCables                        233
Irons,Steamers&Accessories       Irons                             36
Cables                           HDMICables                        24
Irons,Steamers&Accessories       LintShavers                       22
Vacuums&FloorCare                Vacuums                           20
Kettles&HotWaterDispensers       ElectricKettles                   19
Chargers                         WallChargers                      16
Stationery                       Notebooks,WritingPads&Diaries     14
Kettles&HotWaterDispensers       Kettle&ToasterSets                13
Stationery                       Pens,Pencils&WritingSupplies      12
Chargers                         PowerBanks                        12
Keyboard&MiceAccessories         MousePads                          8
Maintenance,Upkeep&Repairs       ScreenProtectors                   7
Bags&Sleeves                     LaptopSleeves&Slipcases            6
TVMounts,Stands&Turntables       TVWall&CeilingMounts               6
Photo&VideoAccessories           SelfieSticks                       5
DeepFatFryers                    AirFryers                          5
Chargers                         AutomobileChargers                 5
Cases&Covers                     BasicCases                         4
AutomobileAccessories            Cradles                            3
CoffeeMakerAccessories           MeasuringSpoons                    3
Cables                           OpticalCables                      3
Cables&Adapters                  OTGAdapters                        2
Cables                           EthernetCables                     2
Tripods&Monopods                 Tabletop&TravelTripods             2
Webcams&VoIPEquipment            Webcams                            2
DigitalKitchenScales             DigitalScales                      2
Tripods&Monopods                 TripodLegs                         2
Mounts                           Bedstand&DeskMounts                2
Mills&Grinders                   WetGrinders                        2
IroningAccessories               SprayBottles                       2
Keyboard&MiceAccessories         DustCovers                         2
Cables                           RCACables                          2
Bags,Cases&Sleeves               Cases                              2
Cleaners                         CleaningKits                       1
CoffeeGrinders                   ElectricGrinders                   1
Cables                           SpeakerCables                      1
                                 SATACables                         1
Batteries&Chargers               BatteryChargers                    1
Cables                           DVICables                          1
DrawingMedia                     Pencils                            1
Copy&PrintingPaper               ColouredPaper                      1
Mounts                           Shower&WallMounts                  1
                                 HandlebarMounts                    1
DrawingMedia                     Pens                               1
Décor                            PhoneCharms                        1
ManualChoppers&Chippers          Choppers                           1
Juicers                          ColdPressJuicers                   1
SmallApplianceParts&Accessories  StandMixerAccessories              1
SpeakerAccessories               Mounts                             1
Photo&VideoAccessories           Tripods                            1
PhotoStudio&Lighting             PhotoBackgroundAccessories         1
Photo&VideoAccessories           Flashes&SelfieLights               1
Tripods&Monopods                 CompleteTripodUnits                1
Vacuums&FloorCare                VacuumAccessories                  1
WeighingScales                   DigitalBathroomScales              1
Name: count, dtype: int64

In [ ]:
df['Product_type'] = df.groupby(['Sub-sub_category'])['Product_type'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category         0
Product_type           884
dtype: int64

In [ ]:
df[['Sub_category','Product_type']].value_counts()

Sub_category                Product_type
Cables & Accessories        USBCables               236
Vacuum,Cleaning & Ironing   Irons                    36
Accessories                 HDMICables               24
Vacuum,Cleaning & Ironing   LintShavers              22
SmallKitchenAppliances      ElectricKettles          20
                                                   ...
MobileAccessories           HandlebarMounts           1
                            Flashes&SelfieLights      1
TraditionalLaptops          USBCables                 1
UninterruptedPowerSupplies  USBCables                 1
Vacuum,Cleaning & Ironing   VacuumAccessories         1
Name: count, Length: 67, dtype: int64

In [ ]:
df['Product_type'] = df.groupby(['Sub_category'])['Product_type'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category         0
Product_type           570
dtype: int64

In [ ]:
df['Product_type'] = df.groupby(['Category'])['Product_type'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id               0
product_name             0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
Root (Department)        0
Category                 0
Sub_category             0
Sub-sub_category         0
Product_type           338
dtype: int64

In [ ]:
df['Product_type'] = df.groupby(['Root (Department)'])['Product_type'] \
                        .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

product_id             0
product_name           0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
Root (Department)      0
Category               0
Sub_category           0
Sub-sub_category       0
Product_type           2
dtype: int64

In [ ]:
df[df['Product_type'].isna()]

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
924,B00DJ5N9VK,Faber-Castell Connector Pen Set - Pack of 25 (...,150.0,150.0,0,4.3,15867.0,Toys & Games,Arts & Crafts,Drawing & PaintingSupplies,ColouringPens&Markers,None
1157,B0912WJ87V,Reffair AX30 [MAX] Portable Air Purifier for C...,2339.0,4000.0,42,3.8,1118.0,Car & Motorbike,CarAccessories,InteriorAccessories,AirPurifiers&Ionizers,None

In [ ]:
df[df['Category']=='CarAccessories']

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,Root (Department),Category,Sub_category,Sub-sub_category,Product_type
1157,B0912WJ87V,Reffair AX30 [MAX] Portable Air Purifier for C...,2339.0,4000.0,42,3.8,1118.0,Car & Motorbike,CarAccessories,InteriorAccessories,AirPurifiers&Ionizers,None

Drop the rows still having values in Product-Type

In [ ]:
df = df.dropna(subset=['Product_type'])
df.shape

(1459, 12)

In [ ]:
df.isnull().sum()

product_id             0
product_name           0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
Root (Department)      0
Category               0
Sub_category           0
Sub-sub_category       0
Product_type           0
dtype: int64

In [ ]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,3135.120925,5461.596491,47.716929,4.096669,18277.867032
std,6956.725119,10893.774335,21.634482,0.291709,42788.295174
min,39.000000,39.000000,0.000000,2.000000,2.000000
25%,325.000000,812.500000,32.000000,4.000000,1186.000000
50%,799.000000,1690.000000,50.000000,4.100000,5179.000000
75%,1999.000000,4331.480000,63.000000,4.300000,17271.500000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

Save the data

In [ ]:
df.to_csv("AmazonCleanedData_Process1.csv", index=False)